image: node:latest

stages:
  # - build
  - test
  - deploy
  
# cache:
#   paths:
#     - front-end/node_modules/

# build_front_end:
#   stage: build
#   script:
#     - cd front-end
#     - npm install
#     - CI=false npm run-script build

jest_tests:
  stage: test
  script:
    - cd front-end
    - npm install
    - npm test

python_unit_tests:
  image: python:3.6-stretch
  stage: test
  before_script:
    - pip install -r back-end/requirements.txt
  script:
    - make python-unit-tests

postman_tests:
  stage: test
  image:
    name: postman/newman_alpine33
    entrypoint: [""]
  script:
    - newman --version
    - newman run Postman.json 

selenium_tests:
  stage: test
  image: nikolaik/python-nodejs
  before_script:
    - pip install -r back-end/requirements.txt
    - pip install selenium==3.141.0 pyvirtualdisplay
    - cd front-end/ && npm install && cd ..
  script:
    - _timeout() { ( set +b; sleep "$1" & "${@:2}" & wait -n; kill -9 `jobs -p`; ) }
    - (_timeout 100 python3 back-end/app.py) &
    - cd front-end/ && (_timeout 100 npm start) &
    - ls
    - python3 guitests.py
    
deploy_development:
  image: python:3.6-stretch
  only:
    variables:
      - $CI_COMMIT_BRANCH == "stage"
  stage: deploy
  before_script:
    - pip install awsebcli --upgrade --user
    - git checkout stage
  script:
    - $AWS_DEV_DEPLOY
    - cd back-end
    - /root/.local/bin/eb deploy Texasvotes-dev

deploy_production:
  image: python:3.6-stretch
  only:
    variables:
      - $CI_COMMIT_BRANCH == "master"
  stage: deploy
  before_script:
    - pip install awsebcli --upgrade --user
    - git checkout master
  script:
    - $AWS_PROD_DEPLOY
    - cd back-end
    - /root/.local/bin/eb deploy Texasvotes-prod
