image: node:latest

stages:
  # - build
  - test
  - deploy
  
# cache:
#   paths:
#     - front-end/node_modules/

# build_front_end:
#   stage: build
#   script:
#     - cd front-end
#     - npm install
#     - CI=false npm run-script build

# jest_tests:
#   stage: test
#   script:
#     - cd front-end
#     - npm install
#     - npm test

# python_unit_tests:
#   image: python:3.6-stretch
#   stage: test
#   before_script:
#     - pip install -r back-end/requirements.txt
#   script:
#     - make python-unit-tests

# postman_tests:
#   stage: test
#   image:
#     name: postman/newman_alpine33
#     entrypoint: [""]
#   script:
#     - newman --version
#     - newman run Postman.json 

selenium_tests:
  stage: test
  image: forbesye/selenium-ci
  before_script:
    - pip install -r front-end/gui_tests/requirements.txt
  script:
    - python3 front-end/guitests.py

deploy_development:
  image: python:3.6-stretch
  only:
    variables:
      - $CI_COMMIT_BRANCH == "stage"
  stage: deploy
  before_script:
    - pip install awsebcli --upgrade --user
    - git checkout stage
  script:
    - $AWS_DEV_DEPLOY
    - cd back-end
    - /root/.local/bin/eb deploy Texasvotes-dev

deploy_production:
  image: python:3.6-stretch
  only:
    variables:
      - $CI_COMMIT_BRANCH == "master"
  stage: deploy
  before_script:
    - pip install awsebcli --upgrade --user
    - git checkout master
  script:
    - $AWS_PROD_DEPLOY
    - cd back-end
    - /root/.local/bin/eb deploy Texasvotes-prod
