# https://hub.docker.com/r/library/node/tags/
image: node:latest
# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache

stages:
  - build
  - test
  - deploy
  
cache:
  paths:
    - front-end/node_modules/

build:
  stage: build
  script:
    - cd front-end
    - npm install
    - npm run-script build

test:
  stage: test
  script:
    - echo "Running React test suite......"

deploy_development:
  only:
    variables:
      - $CI_COMMIT_BRANCH == "stage"
  stage: deploy
  script:
    - $AWS_DEV_DEPLOY

deploy_production:
  only:
    variables:
      - $CI_COMMIT_BRANCH == "master"
  stage: deploy
  script:
    - $AWS_PROD_DEPLOY
