image: node:latest

stages:
  - build
  - test
  - deploy
  
cache:
  paths:
    - front-end/node_modules/

build_front_end:
  stage: build
  script:
    - cd front-end
    - npm install
    - CI=false npm run-script build

test_front_end:
  stage: test
  script:
    - echo "Running React test suite......"

test_back_end:
  image: python:3.6-stretch
  before_script:
    - pip install -r back-end/requirements.txt
  test:
    - python unittests.py -v

deploy_development:
  only:
    variables:
      - $CI_COMMIT_BRANCH == "stage"
  stage: deploy
  script:
    - $AWS_DEV_DEPLOY

deploy_production:
  only:
    variables:
      - $CI_COMMIT_BRANCH == "master"
  stage: deploy
  script:
    - $AWS_PROD_DEPLOY
